spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://141.148.54.169:45432/postgres
    username: devops
    password: M3d3ll1n
    hibernate:
      dbcp:
        initialSize : 5
        maxTotal: 20
        maxIdle: 10
        minIdle: 5
        maxWaitMillis : -1
  application:
    name: evaluacion-docente-api
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  jackson:
    default-property-inclusion: non-null

  rabbitmq:
    host: 129.153.4.42
  zipkin:
    base-url: http://129.80.97.83:9411
    sender:
      type: rabbit
  cloud:
    consul:
      enabled: true
      host: 129.159.67.152
      port: 8500
      discovery:
        instanceId: ${spring.application.name}
        preferIpAddress: true
  sleuth:
    sampler:
      probability: 1.0
rabbit:
  url: amqp://guest:guest@129.153.4.42:5672

logging:
  level:
    root: ERROR
    org:
      hibernate: warn
      apache: warn
      springframework:
        beans: warn
        context: warn
        cloud:
          loadbalancer: warn
        scheduling: warn
        messaging: warn
        boot: error
        web: warn
        jmx: warn
        test: warn
        orm: warn
        security: warn
        data:
          rest: warn

info:
  app:
    version: 1.0.0

server:
  tomcat:
    maxHttpHeaderSize: 10000000
  servlet:
    context-path: /
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json

management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: "*"

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

springdoc:
  show-actuator: false
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /
    operations-sorter: method
    tags-sorter: alpha
    docExpansion: none
