server:
    port: 8084
spring:
    main:
        allow-bean-definition-overriding: true
    application:
    name: evaluacion-docente-api
    # /initiatives-api/api-docs
    rabbitmq:
        host: ${RABBITMQ_HOST:localhost}
    zipkin:
        base-url: ${ZIPKIN_URL:http://localhost:9411}
    cloud:
        consul:
            enabled: true
            host: ${CONSUL_HOST:localhost}
            port: ${CONSUL_PORT:8500}
            discovery:
                instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
                preferIpAddress: true
    sleuth:
        sampler:
            probability: 1.0
rabbit:
    url: ${RABBITMQ_URL = amqp://guest:guest@localhost:5672}

management:
    endpoints:
        health:
            show-details: always
        web:
            exposure:
                include: "*"

spring-doc:
    show-actuator: false
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /
        operations-sorter: method
        tags-sorter: alpha
        docExpansion: none
